<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainLens.Analyzer.Protocol\DomainLens.Analyzer.Protocol.csproj" />
    <ProjectReference Include="..\DomainLens.Core\DomainLens.Core.csproj" />
    <ProjectReference Include="..\DomainLens.Semantics\DomainLens.Semantics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="DomainLens.Analyzer.Protocol" />
  </ItemGroup>

</Project>
