<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainLens.Analyzer.Host\DomainLens.Analyzer.Host.csproj" />
    <ProjectReference Include="..\DomainLens.Core\DomainLens.Core.csproj" />
    <ProjectReference Include="..\DomainLens.Scanner\DomainLens.Scanner.csproj" />
    <ProjectReference Include="..\DomainLens.Semantics\DomainLens.Semantics.csproj" />
  </ItemGroup>

</Project>
