<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Acme.Orders.Domain\Acme.Orders.Domain.csproj" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>
